twig:
    paths:
        '%kernel.project_dir%/templates': App
        '%kernel.project_dir%/vendor/musicjerm/jermbundle/Resources/views': JermBundle
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        app_name: '%app_name%'
        app_short_name: '%app_short_name%'
        app_author: '%app_author%'
        app_version: '%app_version%'
        email_from: '%email_from%'